Test failure #1 

@Test(description="get_backend_services_receiver_positive", enabled=true, groups={"spsp_backend_service_all"})
public void get_backend_services_receiver_positive() {



/*
 * 
 * 3/20/2017 Error:
 *   Test passed     dfsp1-qa   
 *   
 *   
 *  
 *  Test failed on dfsp2-test  :: Looks like the data is the only problem.  Might need to not have the receiver in the file, but created during the test so it can adapt to each environment by creating and retrieving the receiver.  
 *  
    [03-20 20:25:48,860] INFO  [[interop-domain].api-httpListenerConfig.worker.431] spsp-backend-api-main: Received request with traceID=92c0f2b4-d0e6-4c5b-854b-ef7c8c0c40ea at path=/spsp/backend/v1/receivers/54200545
	[03-20 20:25:48,860] INFO  [[interop-domain].api-httpListenerConfig.worker.431] spsp-backend-fetch-payee: Processing request for GET on http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8010/receivers/54200545, traceID=92c0f2b4-d0e6-4c5b-854b-ef7c8c0c40ea, payee=54200545
	[03-20 20:25:48,926] ERROR [[interop-domain].api-httpListenerConfig.worker.431] spsp-backend-fetch-payee: Failed to get account {"id":"Directory.UserNotFound","message":"User not found"}
	[03-20 20:25:48,926] INFO  [[interop-domain].api-httpListenerConfig.worker.431] spsp-backend-fetch-payee: Processing complete for get:/receivers/{payee}, traceID=92c0f2b4-d0e6-4c5b-854b-ef7c8c0c40ea, payee=54200545, payload={"id":"Directory.UserNotFound","message":"User not found"}
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=COUNTER, name=l1p.spsp-backend.fetch.api.FetchPayeeGetRequest, timestamp=1490041549, total_count=118, interval=5, delta=1
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=COUNTER, name=l1p.spsp-backend.payments.api.PaymentsInvoicePostRequest, timestamp=1490041549, total_count=7, interval=5, delta=0
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=COUNTER, name=l1p.spsp-backend.payments.api.PaymentsPayeePutRequest, timestamp=1490041549, total_count=557, interval=5, delta=0
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=TIMER, category=l1p.spsp-backend.fetch.api.FetchPayeeGetTime, timestamp=1490041549, total_count=118, interval=5, delta=1, interval_rate=0.2, m1=6.515301826113625E-59, min=60.195271, max=195.07154699999998, mean=65.93319, p75=65.93319, p95=65.93319, p98=65.93319, p99=65.93319, p999=65.93319, rate_unit=events/second, duration_unit=milliseconds
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=TIMER, category=l1p.spsp-backend.payments.api.PaymentsInvoicePostTime, timestamp=1490041549, total_count=7, interval=5, delta=0, interval_rate=0.0, m1=1.4404152909158775E-84, min=31.007709, max=83.825063, mean=31.387717596304395, p75=31.383271999999998, p95=31.383271999999998, p98=31.383271999999998, p99=31.383271999999998, p999=31.383271999999998, rate_unit=events/second, duration_unit=milliseconds
	[03-20 20:25:49,251] INFO  [metrics-logger-reporter-22-thread-1] metrics: type=TIMER, category=l1p.spsp-backend.payments.api.PaymentsPayeePutTime, timestamp=1490041549, total_count=557, interval=5, delta=0, interval_rate=0.0, m1=5.097512724826319E-58, min=14.052519, max=444.74994699999996, mean=302.9909600938894, p75=362.517496, p95=420.546196, p98=431.297525, p99=435.21588299999996, p999=444.74994699999996, rate_unit=events/second, duration_unit=milliseconds


 *  
 *  
*/



Test Failure #2

@Test(dataProvider="invoice_positive", groups={"spsp_backend_service_all"})
	public void test_get_an_existing_invoice_positive(String personName, String invoiceUrl, String account, String name, String currencyCode, String currencySymbol, String amount, String status, String invoiceInfo) {
		
		
/*	
 * 2/20/2017 Test failed on dfps1 QA for the following reasons.  No errors were logged to server log file, only the console in the test.
 * 
 * 
 * 
 *                                                                                                             *
	**************************************************************************************************************
	Get invoice existing URL: http://ec2-35-163-231-111.us-west-2.compute.amazonaws.com:8088/spsp/client/v1/invoices/{invoiceId}
	Response JSON from call: "Not Found"
	Get invoice existing URL: http://ec2-35-163-231-111.us-west-2.compute.amazonaws.com:8088/spsp/client/v1/invoices/{invoiceId}
	Response JSON from call: "Not Found"
	FAILED: test_get_an_existing_invoice_positive("Bob", "123", "dfsp2.bob.dylan.account", "Bob Dylan", "USD", "$", "10.4", "unpaid", "https://www.example.com/gp/your-account/order-details?ie=UTF8&orderID=111-7777777-1111111")
	io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
		at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
		
		
		
	--------	2/20/2017 Test also failed on dfsp2 test.    ----------
		
		Get invoice existing URL: http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8088/spsp/client/v1/invoices/{invoiceId}
		Response JSON from call: "Not Found"
		Get invoice existing URL: http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8088/spsp/client/v1/invoices/{invoiceId}
		Response JSON from call: "Not Found"
		FAILED: test_get_an_existing_invoice_positive("Bob", "123", "dfsp2.bob.dylan.account", "Bob Dylan", "USD", "$", "10.4", "unpaid", "https://www.example.com/gp/your-account/order-details?ie=UTF8&orderID=111-7777777-1111111")
		io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
			at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
			at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
			at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
			at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
			at io.restassured.path.json.JsonPath.getString(JsonPath.java:351)
			at com.l1.interop.SPSPBackendServiceFunctionalTests.test_get_an_existing_invoice_positive(SPSPBackendServiceFunctionalTests.java:345)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
			at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
			at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
			at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
			at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
			at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
			at org.testng.TestRunner.privateRun(TestRunner.java:767)
			at org.testng.TestRunner.run(TestRunner.java:617)
			at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
			at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
			at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
			at org.testng.SuiteRunner.run(SuiteRunner.java:254)
			at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
			at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
			at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
			at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
			at org.testng.TestNG.run(TestNG.java:1057)
			at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
			at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
			at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
		Caused by: groovy.json.JsonException: A JSON payload should start with an openning curly brace '{' or an openning square bracket '['.
		Instead, '"Not Found"' was found on line: 1, column: 1
			at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		
		
	*/